### ISSUE TITLE
How to change input's value by custom button?

### ISSUE THREAD

**Issue by getsolved** [Itonomy/magento2-bundle-products-change-qty#1]
Hi,
thank you for this extension! I installed it and it works fine. But I use a custom style with plus and minus buttons to increase/decrease the value of the quantity input box. How can I make these buttons work with the current configuration of the bundle? Changing the value of the input box by using the buttons, the current bundle configuration is not changed...
Can you give an advise here?
Thank you!

**Comment by RaphaelBronsveld** [comment]
Hi there,

Thanks for the feedback!
Have you tried invoking a "change" event on the quantity field? Magento has event listeners on the quantity field, so this should update automatically. 

Magento's event listeners are registered in
vendor/magento/module-bundle/view/base/web/js/price-bundle.js (L:68)

Finding the appropriate quantity field (depends on which plus/minus buttons are being pressed) and assign this to a 'qtyField' variable. 

`qtyField.trigger('change');` should work.

Let me know if it does!

Gr, Raphaël

**Comment by getsolved** [comment]
Hi Raphaël,

thank you for your advise! I triggered the onchange event at button click and the product summary updated correctly. Problem solved!

Best regards
Markus
