### ISSUE TITLE
Only 1 product in option: checkbox and quantity field are not shown

### ISSUE THREAD

**Issue by getsolved** [Itonomy/magento2-bundle-products-change-qty#2]
Hi there,

if you have only 1 product in a bundle option group, no checkbox and no quantity field is shown. So this product is always part of the bundle, you cannot remove it or change quantity. It only works with a product count > 1 per group. This behaviour does not make sense for me.

Best regards
Markus

**Comment by RaphaelBronsveld** [comment]
Reproduced! Also made a fix in [1.0.1](https://github.com/Itonomy/magento2-bundle-products-change-qty/releases/tag/1.0.1).

You can run `composer update itonomy/bundleproductchangeqty` to update to these changes.

I pointed out in the release comment that this "fix" compliments the module by also adding this behaviour to "single product" bundle options. Doesn't really make it a bug, just a piece of code that (again) goes against Magento's intended behaviour 😅.

Thanks for the feedback!

**Comment by getsolved** [comment]
Okay...updated extension to 1.0.1.
Quantity field and checkbox is shown now! Testing successful!

Thank you for your quick replies!!!

Best regards
Markus
