### ISSUE TITLE
Problem when add to cart 

### ISSUE THREAD

**Issue by hikken** [Itonomy/magento2-bundle-products-change-qty#3]
Hi, i have problem when Bundle Product is adding to cart, all child item quantity are set at 1 ? In your Model, class Type extends \Magento\Bundle\Model\Product\Type

```
protected function getQty($selection, $qtys, $selectionOptionId)
    {
        if ($selection->getSelectionCanChangeQty() && isset($qtys[$selectionOptionId])) {
            $qty = (float)$qtys[$selectionOptionId] > 0 ? $qtys[$selectionOptionId] : 1;

            var_dump($qty); /*is an array like array(2) { [1]=> string(1) "6" [2]=> string(1) "7" } array(2) { [1]=> string(1) "6" [2]=> string(1) "7" } [] */
        } elseif (isset($qtys[$selectionOptionId][$selection->getId()])) {
            $qty = (float)$qtys[$selectionOptionId][$selection->getId()] ? $qtys[$selectionOptionId][$selection->getId()] : 1;
        } else {
            $qty = (float)$selection->getSelectionQty() ? $selection->getSelectionQty() : 1;
        }

        $qty = (float) $qty; /* array are transforming in float value so 1 */

        return $qty;
    }
}

```

**Comment by RaphaelBronsveld** [comment]
Hi @hikken,

Thanks for the issue report!
What Magento version are you using?

**Comment by giovaneribeiro** [comment]
Hi @hikken and @RaphaelBronsveld.

I've been working on this issue today. What happens is that the first `if` checks if the qtys[] is set, and indeed it is. So the `elseif` that checks if qtys[][] is filled will never be checked.

What I've done to fix is changing the order, so first it checks if the qtys[][] array is set, then if not, it checks if the qtys[] is set.

```
[...]
if ($selection->getSelectionCanChangeQty() && isset($qtys[$selectionOptionId][$selection->getId()])) {
    $qty = (float)$qtys[$selectionOptionId][$selection->getId()] > 0 ? $qtys[$selectionOptionId][$selection->getId()] : 1;
} elseif ($selection->getSelectionCanChangeQty() && isset($qtys[$selectionOptionId])) {
    $qty = (float)$qtys[$selectionOptionId] > 0 ? $qtys[$selectionOptionId] : 1;
[...]
```

I've just found it, so I don't know if there's a future issue doing it.

**Comment by RaphaelBronsveld** [comment]
Hi @giovaneribeiro, @hikken ,

Thank you for your work! 
Could you provide me with a reproduction scenario and magento version? 

- how did you setup the bundle product? (screenshots)
- how does it look on the frontend (screenshots)?

**Comment by giovaneribeiro** [comment]
Hi @RaphaelBronsveld ,
I'm using Magento 2.3.0.

The setup for the bundle product is the same as you've done, I just had to change the order as I mentioned before to solve this issue opened by @hikken .

So instead of adding "1" (which is the default selecion_qty), it adds the input value from the view.

I'm not sending screenshots as the setup and interface kept the same.

**Comment by RaphaelBronsveld** [comment]
Hi @giovaneribeiro , @hikken ,

I have looked for different configurations in the bundle product to try and reproduce this, but I still can't. Based on @hikken 's example, it seems that the `$selection->getSelectionCanChangeQty()` also results to true. It does not result to true in my case; checkbox quantities by default cannot be changed, so this shouldn't happen. 

Custom bundle product on a magento 2.3 installation. This includes 1 option containing 2 checkbox inputs + 1 radio button (just to test "normal" inputs)
![screenshot 2019-02-04 at 11 49 57](https://user-images.githubusercontent.com/42035462/52206292-0ebe8980-287a-11e9-9223-bbb6750d47a0.png)

Adding this to my cart results in this; as expected.
![screenshot 2019-02-04 at 11 50 27](https://user-images.githubusercontent.com/42035462/52206291-0ebe8980-287a-11e9-9fba-67b9ef32f60b.png)

Configuration:
![screenshot 2019-02-04 at 11 50 40](https://user-images.githubusercontent.com/42035462/52206290-0ebe8980-287a-11e9-9c10-9498fa32dbaa.png)

Can you try this as well?

**Comment by giovaneribeiro** [comment]
@RaphaelBronsveld I've just tried your module by itself, and it worked fine.

In my case, I'm also adding the "User Defined" on admin panel to Checkboxes, and when this column `catalog_product_bundle_selection.selection_can_change_qty` is active, your module doesn't work for the option and add "1" by default.

I don't know if is the same case from @hikken, but your module works just fine on Magento 2.3.0, I just have to customize this behavior now. Thank you for your time.

**Comment by RaphaelBronsveld** [comment]
@giovaneribeiro , makes sense! 
This module is build upon a clean Magento installation. Any customizations done within custom code, related to bundled options, will probably break the behaviour.

Thank you as well!
